{% set name = "responsibleai-text" %}
{% set version = "0.2.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/responsibleai_text-{{ version }}.tar.gz
  sha256: 030912182530f8a6a74c3f435cd651dc466dd6cc28ca7505f054558183b9cebf

build:
  noarch: python
  script:
    - cp -R {{ RECIPE_DIR }}/requirements.txt {{ SRC_DIR }}/requirements.txt  # [unix]
    - echo f | xcopy /f /y /S %RECIPE_DIR%\requirements.txt %SRC_DIR%\requirements.txt  # [win]
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - numpy >=1.17.2
    - pandas >=0.25.1
    - scikit-learn >=0.22.1
    - scipy >=1.4.1
    - semver >=2.13.0,<2.14.dev0
    - nlp-feature-extractors ==0.1.0
    - responsibleai >=0.35.0

test:
  imports:
    - responsibleai_text
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/microsoft/responsible-ai-toolbox
  summary: SDK API to assess text Machine Learning models.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
